// Metric glossary. The UI shows these strings verbatim and docs/api/analysis.md
// is generated from this file (tools/analysis/make-glossary.mjs), so the two
// never disagree.
//
// Fields: label, meaning (one line, for a non-specialist), formula (or
// reference), needs (directed / weighted / full view ...), reliability.

export const GLOSSARY = {
  // ---- node ----
  contacts: { level: 'node', label: 'Contacts', meaning: 'How many different people this person has a tie with, in either direction.', formula: 'Distinct neighbors. Directed networks: in-degree + out-degree minus the two-way ties counted twice (degree x (1 - reciprocity / 2)); undirected networks: degree.', needs: 'Any network.', reliability: 'Robust. Depends directly on the construction rules and the broadcast cutoff; a one-time contact counts the same as a daily one.' },
  degree: { level: 'node', label: 'Degree', meaning: 'Number of ties. On a directed network, ties in plus ties out, so a two-way tie counts twice; Contacts counts each person once.', formula: 'Number of ties. Directed networks: in-degree + out-degree (a two-way tie counts twice), as networkx.', needs: 'Any network.', reliability: 'Robust. Depends directly on the construction rules and the broadcast cutoff.' },
  inDegree: { level: 'node', label: 'In-degree', meaning: 'How many people direct messages, replies or nominations at this person.', formula: 'Number of incoming ties.', needs: 'Directed network.', reliability: 'Robust in full views; in one person\'s export only the owner\'s incoming ties are complete.' },
  outDegree: { level: 'node', label: 'Out-degree', meaning: 'How many people this person reaches out to.', formula: 'Number of outgoing ties.', needs: 'Directed network.', reliability: 'Robust in full views.' },
  strength: { level: 'node', label: 'Strength', meaning: 'Total volume of this person\'s ties: how much interaction, not just with how many people.', formula: 'Sum of tie weights (in + out for directed networks).', needs: 'Weighted network (count or log weighting).', reliability: 'Heavily skewed by a few very active ties; compare with degree. Log weighting dampens this.' },
  inStrength: { level: 'node', label: 'In-strength', meaning: 'Total volume of interaction directed at this person.', formula: 'Sum of incoming tie weights.', needs: 'Directed, weighted network.', reliability: 'As strength.' },
  outStrength: { level: 'node', label: 'Out-strength', meaning: 'Total volume of interaction this person initiates.', formula: 'Sum of outgoing tie weights.', needs: 'Directed, weighted network.', reliability: 'As strength.' },
  betweenness: { level: 'node', label: 'Betweenness', meaning: 'How often this person sits on the shortest route between two others: a potential bridge or bottleneck.', formula: 'Brandes (2001). Share of ordered pairs (s, t) whose shortest paths pass through the node, split across tied paths: raw / ((n-1)(n-2)). Ties are not weighted.', needs: 'A full view of the group; not meaningful for one person\'s export.', reliability: 'Ignores tie weights: the weighting setting (count, log, binary) does not change it. Sensitive to missing ties and to the construction rules; check the rank interval from resampling before calling someone a broker. Approximate (sampled sources) above 3,000 people unless exact is requested.' },
  betweennessWeighted: { level: 'node', label: 'Betweenness (weighted)', meaning: 'As betweenness, but routes prefer strong ties: a strong tie counts as a short step.', formula: 'Brandes with Dijkstra, distance = 1 / weight; same normalization. Equal-length paths are detected with a relative tolerance of 1e-10.', needs: 'Weighted network; full view.', reliability: 'More sensitive than unweighted betweenness to the weighting choice (count vs log).' },
  closeness: { level: 'node', label: 'Closeness (harmonic)', meaning: 'How easily others can reach this person in few steps.', formula: 'Harmonic closeness: sum over others of 1 / d(other, node), divided by n-1 (Marchiori and Latora 2000; Boldi and Vigna 2014). Unreachable people add 0. Directed: distances toward the node.', needs: 'Full view.', reliability: 'Ignores tie weights. Defined on disconnected networks, but people in small components score low partly because they cannot reach the rest.' },
  closenessWeighted: { level: 'node', label: 'Closeness (weighted)', meaning: 'As closeness, with strong ties counting as short steps.', formula: 'Harmonic closeness with distance = 1 / weight, divided by n-1.', needs: 'Weighted network; full view.', reliability: 'Scale depends on the weighting; compare people within one network only.' },
  eigenvector: { level: 'node', label: 'Eigenvector centrality', meaning: 'Connected to people who are themselves well connected.', formula: 'Leading eigenvector of the symmetrized weighted adjacency matrix (w(a,b) + w(b,a)), unit Euclidean norm; power iteration on A + I so bipartite networks converge (as networkx).', needs: 'A connected full view. Directed networks are symmetrized; use PageRank for a directional version.', reliability: 'Not comparable across components: scores outside the largest component shrink toward zero. Scores from different networks are on different scales; compare ranks, not values.' },
  pagerank: { level: 'node', label: 'PageRank', meaning: 'Receives attention from people who themselves receive attention (directional status).', formula: 'Brin and Page (1998), damping 0.85, weighted, dangling nodes redistribute uniformly (as networkx). Sums to 1.', needs: 'Directed network gives the directional reading; undirected gives a smoothed degree.', reliability: 'Values shrink as the network grows (they sum to 1); compare ranks across networks.' },
  clustering: { level: 'node', label: 'Clustering', meaning: 'How many of this person\'s contacts also know each other.', formula: 'Local clustering coefficient on the symmetrized, unweighted network: ties among neighbors / (k(k-1)/2) (Watts and Strogatz 1998).', needs: 'Full view (in one person\'s export, ties among their contacts are mostly invisible).', reliability: 'Undefined (0) for people with fewer than two contacts; meetings inflate it.' },
  coreNumber: { level: 'node', label: 'Core number', meaning: 'How deep in the densely connected core this person sits.', formula: 'Largest k such that the person belongs to a subgraph where everyone has at least k ties (Batagelj and Zaversnik 2003), symmetrized network.', needs: 'Full view.', reliability: 'Robust; coarse (integer).' },
  reciprocity: { level: 'node', label: 'Reciprocity', meaning: 'Share of this person\'s ties that go both ways.', formula: '2 x |in-neighbors AND out-neighbors| / (in-degree + out-degree), as networkx.', needs: 'Directed network.', reliability: 'Inflated when turn-taking (adjacency) ties are on.' },
  constraint: { level: 'node', label: 'Constraint', meaning: 'How much this person\'s contacts are tied to each other: high = embedded in one closed group; low = spans separate groups (Burt\'s structural holes).', formula: 'Burt (1992): sum over contacts j of (p_ij + sum_q p_iq p_qj)^2, p = share of i\'s total mutual tie weight w(i,j) + w(j,i), as networkx.', needs: 'Full view; weighted.', reliability: 'People with one contact always score 1. Use with effective size; check the per-person null model before calling someone a broker.' },
  effectiveSize: { level: 'node', label: 'Effective size', meaning: 'Number of non-redundant contacts: contacts who do not already know each other.', formula: 'Burt (1992): sum over contacts j of (1 - sum_q p_iq m_jq), m = tie weight / j\'s strongest tie (as networkx). Unweighted undirected equals n - 2t/n (Borgatti 1997).', needs: 'Full view; weighted.', reliability: 'Grows with degree; efficiency = effective size / degree compares people with different numbers of contacts.' },
  egoDensity: { level: 'node', label: 'Ego density', meaning: 'Share of possible ties among this person\'s contacts that exist.', formula: 'Ties among alters / possible ties. Undirected: equals clustering. Directed: directed ties among alters / k(k-1).', needs: 'Full view, or an ego-network survey with alter-alter ties.', reliability: 'Undefined with fewer than two contacts.' },

  // ---- network ----
  density: { level: 'network', label: 'Density', meaning: 'Share of all possible ties that exist.', formula: 'm / (n(n-1)) directed; 2m / (n(n-1)) undirected.', needs: 'Full view.', reliability: 'Falls with network size by construction; compare networks of similar size only.' },
  reciprocityNetwork: { level: 'network', label: 'Reciprocity', meaning: 'Share of ties that are returned.', formula: 'Reciprocated directed ties / all directed ties (networkx overall_reciprocity).', needs: 'Directed network.', reliability: 'Compare with the null model: degree sequences alone produce some reciprocity.' },
  transitivity: { level: 'network', label: 'Transitivity', meaning: 'How often a friend of a friend is also a friend.', formula: '3 x triangles / connected triples, symmetrized unweighted network.', needs: 'Full view.', reliability: 'Meetings create cliques and inflate it; check the null model.' },
  avgClustering: { level: 'network', label: 'Average clustering', meaning: 'Average of each person\'s clustering.', formula: 'Mean local clustering, people with fewer than two contacts counted as 0 (networkx).', needs: 'Full view.', reliability: 'Dominated by low-degree people; transitivity weights by triples instead.' },
  components: { level: 'network', label: 'Components', meaning: 'Number of separate pieces: groups with no tie path between them.', formula: 'Weakly connected components (isolates each count as one).', needs: 'Any.', reliability: 'Very sensitive to the time window and filters.' },
  largestComponentShare: { level: 'network', label: 'Largest component', meaning: 'Share of people in the biggest connected piece.', formula: 'Size of the largest weak component / n.', needs: 'Any.', reliability: 'Robust.' },
  avgPathLength: { level: 'network', label: 'Average path length', meaning: 'Typical number of steps between two people who can reach each other.', formula: 'Mean shortest-path length over reachable ordered pairs (unweighted). Exact up to 2,000 people, sampled from 500 sources above.', needs: 'Full view.', reliability: 'Ignores unreachable pairs, so a fragmented network can look short.' },
  diameter: { level: 'network', label: 'Diameter', meaning: 'The longest shortest route between any two connected people.', formula: 'Maximum finite shortest-path length (lower bound when sampled).', needs: 'Full view.', reliability: 'Driven by a single path; fragile.' },
  degreeCentralization: { level: 'network', label: 'Degree centralization', meaning: 'How much ties concentrate on one person (1 = a star, 0 = everyone equal).', formula: 'Freeman (1979): sum (max degree - degree_i) / ((n-1)(n-2)), symmetrized.', needs: 'Full view.', reliability: 'Driven by the single most connected person; check who that is.' },
  strengthGini: { level: 'network', label: 'Strength inequality (Gini)', meaning: 'How unequally interaction volume is spread across people (0 = equal, 1 = one person has it all).', formula: 'Gini coefficient of node strength.', needs: 'Weighted network.', reliability: 'Isolates count as zeros and raise it.' },
  degreeAssortativity: { level: 'network', label: 'Degree assortativity', meaning: 'Whether well-connected people connect with each other (positive) or with the less connected (negative).', formula: 'Newman (2002) Pearson correlation of degree across tie ends; directed: source out-degree vs target in-degree (networkx).', needs: 'Full view.', reliability: 'Compare with the null model; hubs in small networks force negative values.' },
  modularity: { level: 'network', label: 'Modularity', meaning: 'How cleanly the network splits into groups with many ties inside and few between.', formula: 'Newman (2004): sum_c [W_c/W - resolution (S_c/2W)^2], symmetrized weighted network.', needs: 'Full view.', reliability: 'Louvain finds high modularity even in random networks; compare with the null model and other seeds.' },
  communities: { level: 'network', label: 'Communities', meaning: 'Groups of people more tied to each other than to the rest, found from the ties alone.', formula: 'Louvain (Blondel et al. 2008) on the symmetrized weighted network, seeded; ids ordered by first member.', needs: 'Full view.', reliability: 'Different seeds and resolutions give different splits; small communities are unstable.' },

  // ---- groups ----
  eiIndex: { level: 'group', label: 'E-I index', meaning: 'Whether ties mostly stay inside groups (toward -1) or cross them (toward +1).', formula: 'Krackhardt and Stern (1988): (external - internal) / (external + internal) ties, people with a value only.', needs: 'A categorical attribute with good coverage.', reliability: 'Depends on group sizes: big groups have more internal options. Compare with the null model.' },
  assortativity: { level: 'group', label: 'Attribute assortativity', meaning: 'Whether people tie to others in their own group more than chance mixing would give (1 = only within, 0 = random, negative = across).', formula: 'Newman (2003) categorical assortativity from the tie-end mixing matrix (networkx attribute_assortativity_coefficient).', needs: 'Categorical attribute.', reliability: 'Corrects for group size, unlike E-I; check the null model.' },
  numericAssortativity: { level: 'group', label: 'Numeric assortativity', meaning: 'Whether people tie to others with similar values (tenure, level).', formula: 'Pearson correlation of the attribute across tie ends (networkx numeric_assortativity_coefficient).', needs: 'Numeric attribute.', reliability: 'Linear only.' },
  groupDensity: { level: 'group', label: 'Within / between density', meaning: 'Share of possible ties that exist inside a group, or between two groups.', formula: 'Ties / possible ties for that block of the mixing matrix.', needs: 'Categorical attribute; full view.', reliability: 'Noisy for groups of a few people.' },

  // ---- ego ----
  egoSize: { level: 'ego', label: 'Network size', meaning: 'Number of distinct contacts.', formula: 'Neighbors in the symmetrized network.', needs: 'Any.', reliability: 'Robust.' },
  efficiency: { level: 'ego', label: 'Efficiency', meaning: 'Share of contacts that are non-redundant.', formula: 'Effective size / size.', needs: 'Ties among contacts.', reliability: 'Undefined without contacts.' },
  diversity: { level: 'ego', label: 'Contact diversity', meaning: 'How varied this person\'s contacts are on an attribute (0 = all alike).', formula: 'Blau index 1 - sum p_k^2 over attribute values; normalized version divides by 1 - 1/K.', needs: 'An attribute for contacts.', reliability: 'Depends on how many values the attribute has.' },
  homophily: { level: 'ego', label: 'Same-group share', meaning: 'Share of this person\'s contacts who share their attribute value.', formula: 'Contacts with the same value / contacts with a value. egoEI = (different - same) / total.', needs: 'Attribute for ego and contacts.', reliability: 'Compare with the group\'s share of the population.' },

  // ---- uncertainty ----
  nullZ: { level: 'uncertainty', label: 'z vs random', meaning: 'How far the observed value is from networks with the same degrees but random wiring, in standard deviations.', formula: '(observed - mean of randomized) / sd of randomized. Directed: in/out-degree-preserving edge swaps; undirected: double edge swaps (10 swaps per tie per replicate).', needs: 'Enough ties to rewire.', reliability: 'Read together with p; with few replicates p cannot go below 1/(reps+1).' },
  nullP: { level: 'uncertainty', label: 'p vs random', meaning: 'Share of randomized networks at least as extreme as the observed one.', formula: 'Empirical two-sided p = (count of |null - mean| >= |obs - mean| + 1) / (reps + 1).', needs: 'As z.', reliability: 'Smallest possible value is 1/(reps+1).' },
  rankInterval: { level: 'uncertainty', label: 'Rank interval', meaning: 'Range of ranks this person gets when the events are resampled: a narrow range near the top is a finding; a wide one is not.', formula: 'Bootstrap over events (resample with replacement, rebuild, recompute), 2.5th-97.5th percentile of rank.', needs: 'Event data (not hand-drawn ties).', reliability: 'Measures sampling noise in the events, not missing data or construction choices.' },
  topShare: { level: 'uncertainty', label: 'Top-k share', meaning: 'Share of resamples in which this person is in the top k.', formula: 'Count of resamples with rank <= k / reps.', needs: 'As rank interval.', reliability: 'As rank interval.' },

  // ---- time ----
  tieTurnover: { level: 'time', label: 'Tie turnover', meaning: 'Ties formed and dropped between consecutive windows, and the overlap.', formula: 'Formed = new ties; dissolved = ties not seen again; Jaccard = kept / union.', needs: 'Timestamps.', reliability: 'Short windows show churn that is just sampling; prefer weeks or months.' },
  shiftZ: { level: 'time', label: 'Shift (robust z)', meaning: 'How unusual a window is compared with the preceding windows.', formula: '(value - median of previous 8 windows) / (1.4826 x MAD), floored at 5% of the median; |z| >= 3.5 flags. CUSUM alternative: two-sided, k = 0.5, h = 5.', needs: 'At least 4-8 windows of baseline.', reliability: 'Holidays and reporting gaps also produce shifts; check the events.' },
  dz: { level: 'time', label: 'Effect size (d_z)', meaning: 'Size of the average per-person change before vs after a date, in standard deviations of the changes.', formula: 'Mean of paired differences / sd of differences; p from a sign-flip permutation test.', needs: 'Timestamps on both sides of the date.', reliability: 'Not causal: anything else that changed at the date counts too.' },

  // ---- content ----
  sentiment: { level: 'content', label: 'Sentiment (compound)', meaning: 'Average tone of messages, from -1 (negative) to +1 (positive).', formula: 'VADER compound score (Hutto and Gilbert 2014), averaged; positive >= 0.05, negative <= -0.05.', needs: 'English message text.', reliability: 'Approximate: misses sarcasm, jargon and non-English text. Compare averages over many messages.' },
  tfidf: { level: 'content', label: 'Distinctive words (TF-IDF)', meaning: 'Words a person or group uses more than others.', formula: 'tf (share of the unit\'s words) x smooth idf ln((1+U)/(1+df))+1 over units.', needs: 'Message text.', reliability: 'Units with little text produce noisy lists.' },
  topics: { level: 'content', label: 'Topics (LDA)', meaning: 'Recurring clusters of words, and how much each person or period talks about each.', formula: 'Latent Dirichlet allocation, collapsed Gibbs sampling (Griffiths and Steyvers 2004), seeded; alpha 0.1, beta 0.01.', needs: 'Several hundred messages with text.', reliability: 'Exploratory: change k or the seed and topics change.' },
  exposedShare: { level: 'content', label: 'Exposed adoption', meaning: 'Share of people who started using a word after someone they are tied to had used it.', formula: 'Adopters (after the first) with an earlier-adopting neighbor / adopters; compared with adoption times shuffled among the same adopters.', needs: 'Timestamps, text and a full view.', reliability: 'Exposure is not influence: tied people share meetings and news. Trust only a clear excess over the shuffle null.' },
};

export function glossaryFor(metric) { return GLOSSARY[metric] || null; }
